var abortionDetails=

[{"state":"AK","law":"insurance","ID":"AK_insurance_1","details":"Legislation was passed to limit Medicaid abortion coverage to cases of rape or incest, or to save the life of the mother, but Alaska's attorney general is contesting the legality of such a restriction"},
{"state":"AL","law":"providers","ID":"AL_providers_1","details":"Amends abortion reporting requirements"},
{"state":"AL","law":"timing","ID":"AL_timing_1","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"AL","law":"insurance","ID":"AL_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"AR","law":"clinic","ID":"AR_clinic_1","details":"Arkansas requires providers that perform at least 10 abortions per month"},
{"state":"AZ","law":"clinic","ID":"AZ_clinic_1","details":"Prohibits the use of telemedicine limited only to abortion medication"},
{"state":"AZ","law":"clinic","ID":"AZ_clinic_2","details":"Requires some or all providers to secure admitting privileges at local hospitals"},
{"state":"AZ","law":"clinic","ID":"AZ_clinic_3","details":"Requires patients to have an ultrasound 24 hours before an abortion"},
{"state":"AZ","law":"clinic","ID":"AZ_clinic_4","details":"Rather than use the new off-label protocol for medication, these states mandate that providers use an outdated, more expensive FDA protocol"},
{"state":"AZ","law":"clinic","ID":"AZ_clinic_5","details":"Requires specific counseling on negative mental health impact of an abortion"},
{"state":"AZ","law":"counseling","ID":"AZ_counseling_1","details":"Requires specific counseling on fetus impairment: information about perinatal hospice if the woman's fetus has a lethal abnormality, or if the abnormality is not lethal, information on the outcomes for those living with physical, developmental, educational, and mental conditions"},
{"state":"AZ","law":"counseling","ID":"AZ_counseling_2","details":"Requires specific counseling on negative mental health impact of an abortion"},
{"state":"AZ","law":"providers","ID":"AZ_providers_1","details":"Prohibits lawsuit if the failure to provide information leads the woman to continue her pregnancy"},
{"state":"AZ","law":"providers","ID":"AZ_providers_2","details":"Prohibits physician assistants from providing abortions"},
{"state":"AZ","law":"providers","ID":"AZ_providers_3","details":"Prohibits nurses from providing abortions"},
{"state":"AZ","law":"providers","ID":"AZ_providers_4","details":"Amends abortion reporting requirements"},
{"state":"AZ","law":"timing","ID":"AZ_timing_1","details":"Bans abortion at 18 weeks post-fertilization (20 weeks after the woman's last period)"},
{"state":"AZ","law":"timing","ID":"AZ_timing_2","details":"Bans abortion for race or sex selection"},
{"state":"FL","law":"clinic","ID":"FL_clinic_1","details":"Requires patients to have an ultrasound before an abortion"},
{"state":"FL","law":"minors","ID":"FL_minors_1","details":"Amends judicial bypass process for minors"},
{"state":"FL","law":"insurance","ID":"FL_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"GA","law":"providers","ID":"GA_providers_1","details":"Amends abortion reporting requirements"},
{"state":"GA","law":"minors","ID":"GA_minors_1","details":"Requires reporting of statutory rape by reproductive health facilities"},
{"state":"GA","law":"timing","ID":"GA_timing_1","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"IA","law":"Insurance","ID":"IA_insurance_1","details":"Limits Medicaid abortion coverage to cases of rape or incest, or to save the life of the mother"},
{"state":"IA","law":"Insurance","ID":"IA_insurance_2","details":"Continues state Medicaid funding restrictions on abortion"},
{"state":"ID","law":"providers","ID":"ID_providers_1","details":"Amends abortion reporting requirements"},
{"state":"ID","law":"timing","ID":"ID_timing_1","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"ID","law":"insurance","ID":"ID_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"IN","law":"clinic","ID":"IN_clinic_1","details":"Requires providers to secure admitting privileges at local hospitals"},
{"state":"IN","law":"counseling","ID":"IN_counseling_1","details":"Requires counseling to include a statement that the fetus is a person"},
{"state":"IN","law":"counseling","ID":"IN_counseling_2","details":"Requires counseling to include a description of fetal pain"},
{"state":"IN","law":"counseling","ID":"IN_counseling_3","details":"Requires counseling to include information about fetal development and resources to help the woman continue the pregnancy"},
{"state":"IN","law":"minors","ID":"IN_minors_1","details":"Requires courts or clinics to collect data on minors&rsquo; abortions"},
{"state":"IN","law":"minors","ID":"IN_minors_2","details":"Amends judicial bypass process for minors"},
{"state":"IN","law":"timing","ID":"IN_timing_1","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"IN","law":"insurance","ID":"IN_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"IN","law":"providers","ID":"IN_providers_1","details":"Amends abortion reporting requirements"},
{"state":"kansas","law":"clinic","ID":"KS_clinic_1","details":"Prohibits the use of telemedicine limited only to abortion medication"},
{"state":"kansas","law":"clinic","ID":"KS_clinic_2","details":"Requires providers to secure admitting privileges at local hospitals"},
{"state":"kansas","law":"clinic","ID":"KS_clinic_3","details":"Rather than use the new off-label <br> protocol for medication, these states mandate that providers use an <br> outdated, more expensive FDA protocol"},
{"state":"kansas","law":"clinic","ID":"KS_clinic_4","details":"Requires the state to develop new regulations on abortion clinics"},
{"state":"kansas","law":"clinic","ID":"KS_clinic_5","details":"Requires patients to have an <br> ultrasound before an abortion"},
{"state":"kansas","law":"counseling","ID":"KS_counseling_1","details":"Requires counseling to include a statement that the fetus is a person"},
{"state":"kansas","law":"providers","ID":"KS_providers_1","details":"Prohibits state agencies or employees from participating in abortions"},
{"state":"kansas","law":"providers","ID":"KS_providers_2","details":"Allows health-care facilities to refuse to participate in and refer for abortion"},
{"state":"kansas","law":"providers","ID":"KS_providers_3","details":"Allows any hospital or clinic employee to refuse to refer for abortion"},
{"state":"kansas","law":"providers","ID":"KS_providers_4","details":"Amends abortion reporting requirements"},
{"state":"kansas","law":"minors","ID":"KS_minors_1","details":"Requires courts or clinics to collect data on minors&rsquo; abortions"},
{"state":"kansas","law":"minors","ID":"KS_minors_2","details":"Requires parental consent before a minor obtains an abortion"},
{"state":"kansas","law":"minors","ID":"KS_minors_3","details":"Amends judicial bypass process for minors"},
{"state":"kansas","law":"timing","ID":"KS_timing_1","details":"Limits abortion after fetal viability"},
{"state":"kansas","law":"timing","ID":"KS_timing_2","details":"Revises &ldquo;partial birth&rdquo; abortion ban to mirror federal law"},
{"state":"kansas","law":"timing","ID":"KS_timing_3","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"kansas","law":"insurance","ID":"KS_insurance_1","details":"Limits abortion coverage in all private health plans"},
{"state":"kansas","law":"insurance","ID":"KS_insurance_2","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"LA","law":"clinic","ID":"LA_clinic_1","details":"Requires providers to display and describe the ultrasound image"},
{"state":"LA","law":"counseling","ID":"LA_counseling_1","details":"Requires providers to make the fetal heartbeat audible to patients"},
{"state":"LA","law":"providers","ID":"LA_providers_1","details":"Requires providers to be physicians"},
{"state":"LA","law":"timing","ID":"LA_timing_1","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"MD","law":"insurance","ID":"MD_insurance_1","details":"Continues state Medicaid funding restrictions on abortion"},
{"state":"MD","law":"insurance","ID":"MD_insurance_2","details":"Continues state Medicaid funding restrictions on abortion"},
{"state":"michigan","law":"clinic","ID":"MI_clinic_1","details":"Prohibits the use of <br> telemedicine"},
{"state":"michingan","law":"clinic","ID":"MI_clinic_2","details":"Requires state to develop new <br> regulations on abortion clinics"},
{"state":"michingan","law":"timing","ID":"MI_timing_1","details":"Revises &ldquo;partial birth&rdquo; abortion ban to mirror federal law"},
{"state":"missouri","law":"providers","ID":"MO_providers_1","details":"Amends abortion <br> reporting requirements"},
{"state":"missouri","law":"timing","ID":"MO_timing_1","details":"Limits abortion after fetal viability"},
{"state":"missouri","law":"insurance","ID":"MO_insurance_1","details":"Allows an employer, enrollee, or insurer to deny coverage of abortion"},
{"state":"MS","law":"clinic","ID":"MS_clinic_1","details":"Requires some or all providers to secure admitting privileges at local hospitals"},
{"state":"MS","law":"providers","ID":"MS_providers_1","details":"Requires providers to secure OB/GYN certification"},
{"state":"MS","law":"minors","ID":"MS_minors_1","details":"Requires reporting of statutory rape by reproductive health facilities"},
{"state":"MT","law":"minors","ID":"MT_minors_1","details":"Requires parental notification before a minor obtains an abortion"},
{"state":"nebraska","law":"clinic","ID":"NE_clinic_1","details":"Prohibits the use of <br> telemedicine limited <br> only to abortion <br> medication"},
{"state":"nebraska","law":"minors","ID":"NE_minors_1","details":"Requires courts or clinics to <br> collect data on minors&rsquo; abortions"},
{"state":"nebraska","law":"minors","ID":"NE_minors_2","details":"Requires parental consent before <br> a minor obtains an abortion"},
{"state":"nebraska","law":"minors","ID":"NE_minors_3","details":"Amends judicial bypass <br> process for minors"},
{"state":"nebraska","law":"insurance","ID":"NE_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"nebraska","law":"insurance","ID":"NE_insurance_2","details":"Limits abortion coverage in all private health plans"},
{"state":"NH","law":"minors","ID":"NH_minors_1","details":"Amends judicial bypass process for minors"},
{"state":"NH","law":"minors","ID":"NH_minors_2","details":"Requires parental notification before a minor obtains an abortion"},
{"state":"NH","law":"timing","ID":"NH_timing_1","details":"Bans &ldquo;partial birth&rdquo; abortions"},
{"state":"north dakota","law":"clinic","ID":"ND_clinic_1","details":"Prohibits the use of <br> telemedicine limited <br> only to abortion <br> medication"},
{"state":"north dakota","law":"clinic","ID":"ND_clinic_2","details":"Rather than use <br> the new off-label <br> protocol for <br> medication, these <br> states mandate <br> that providers <br> use an outdated, <br> more expensive <br> FDA protocol"},
{"state":"north dakota","law":"clinic","ID":"ND_clinic_3","details":"Limits provisions <br> so that only <br> physicians can <br> provide abortions"},
{"state":"north dakota","law":"clinic","ID":"ND_clinic_4","details":"Requires providers <br> to contract with <br> a physician who <br> has hospital <br> privileges"},
{"state":"north dakota","law":"counseling","ID":"ND_counseling_1","details":"North Dakota requires <br> warnings about the <br> increased risk of <br> breast cancer due <br> to an abortion, <br> a claim proven <br> false by the National <br> Cancer Institute"},
{"state":"north dakota","law":"counseling","ID":"ND_counseling_2","details":"Requires counseling to <br> include information about <br> fetal development and <br> resources to help <br> the woman continue <br> the pregnancy"},
{"state":"north dakota","law":"providers","ID":"ND_providers_1","details":"Amends abortion reporting <br> requirements"},
{"state":"north dakota","law":"minors","ID":"ND_minors_1","details":"Requires courts or clinics to <br> collect data on minors&rsquo; abortions"},
{"state":"north dakota","law":"minors","ID":"ND_minors_2","details":"Amends judicial bypass <br> process for minors"},
{"state":"OH","law":"minors","ID":"OH_minors_1","details":"Amends judicial bypass process for minors"},
{"state":"OH","law":"timing","ID":"OH_timing_1","details":"Limits abortion after fetal viability"},
{"state":"OH","law":"insurance","ID":"OH_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"oklahoma","law":"clinic","ID":"OK_clinic_1","details":"Prohibits the use of <br> telemedicine limited <br> only to abortion <br> medication"},
{"state":"oklahoma","law":"clinic","ID":"OK_clinic_2","details":"Rather than use the <br> new off-label <br> protocol for <br> medication, these <br> states mandate that <br> providers use an <br> outdated, more <br> expensive FDA <br> protocol"},
{"state":"oklahoma","law":"clinic","ID":"OK_clinic_3","details":"Prohibits the use of <br> telemedicine limited <br> only to abortion <br> medication"},
{"state":"oklahoma","law":"counseling","ID":"OK_counseling_1","details":"Requires providers to offer <br> patients the option to <br> listen to the fetal heartbeat"},
{"state":"oklahoma","law":"providers","ID":"OK_providers_1","details":"Allows lawsuits against providers <br> for any violation of <br> state abortion regulations"},
{"state":"oklahoma","law":"providers","ID":"OK_providers_2","details":"Amends abortion reporting <br> requirements"},
{"state":"oklahoma","law":"timing","ID":"OK_timing_1","details":"Bans abortion at 20 weeks post-fertilization (22 weeks after the woman's last period)"},
{"state":"oklahoma","law":"insurance","ID":"OK_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"oklahoma","law":"insurance","ID":"OK_insurance_2","details":"Limits abortion coverage in all private health plans"},
{"state":"PA","law":"clinic","ID":"PA_clinic_1","details":"Requires the state to develop new regulations on abortion clinics"},
{"state":"NC","law":"clinic","ID":"NC_clinic_1","details":"Requires courts or clinics to collect data on minors&rsquo; abortions"},
{"state":"NC","law":"insurance","ID":"NC_insurance_1","details":"Limits abortion coverage in state employee health plan"},
{"state":"NC","law":"insurance","ID":"NC_counseling_1","details":"Requires counseling"},
{"state":"NC","law":"insurance","ID":"NC_counseling_2","details":"Requires a 24-hour waiting period"},
{"state":"SC","law":"insurance","ID":"SC_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"SD","law":"clinic","ID":"SD_clinic_1","details":"Prohibits the use of telemedicine <br> limited only to abortion medication"},
{"state":"SD","law":"counseling","ID":"SD_counseling_1","details":"South Dakota enacted <br> regulations that require <br> counseling about <br> dubious risk factors"},
{"state":"SD","law":"counseling","ID":"SD_counseling_2","details":"Extends the waiting period before an abortion from 24 to 72 hours"},
{"state":"SD","law":"counseling","ID":"SD_counseling_3","details":"Adds requirements for crisis <br> pregnancy centers that <br> register with the state for <br> counseling purposes"},
{"state":"SD","law":"counseling","ID":"SD_counseling_4","details":"Requires a visit to a crisis pregnancy center before obtaining an abortion"},
{"state":"SD","law":"counseling","ID":"SD_counseling_5","details":"Requires in-person counseling <br> for all or some women"},
{"state":"SD","law":"counseling","ID":"SD_counseling_6","details":"Requires specific counseling <br> on negative mental health <br> impact of an abortion"},
{"state":"SD","law":"insurance","ID":"SD_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"TN","law":"clinic","ID":"TN_clinic_1","details":"Prohibits the use of telemedicine limited only to abortion medication"},
{"state":"TN","law":"clinic","ID":"TN_clinic_2","details":"Changes effective date of telemedicine ban"},
{"state":"TN","law":"clinic","ID":"TN_clinic_3","details":"Requires some or all providers to secure admitting privileges at local hospitals"},
{"state":"TX","law":"clinic","ID":"TX_clinic_1","details":"Requires patients to have an ultrasound before an abortion"},
{"state":"TX","law":"counseling","ID":"TX_counseling_1","details":"Requires in-person counseling for all or some women"},
{"state":"TX","law":"counseling","ID":"TX_counseling_2","details":"Requires counseling to include information about fetal development and resources to help the woman continue the pregnancy"},
{"state":"TX","law":"providers","ID":"TX_providers_1","details":"Amends abortion reporting requirements"},
{"state":"UT","law":"clinic","ID":"UT_clinic_1","details":"Requires the state to develop new regulations on abortion clinics"},
{"state":"UT","law":"counseling","ID":"UT_counseling_1","details":"Extends the waiting period before an abortion from 24 to 72 hours"},
{"state":"UT","law":"providers","ID":"UT_providers_1","details":"Allows public and non-religious hospitals and any health clinic to refuse to perform an abortion"},
{"state":"UT","law":"providers","ID":"UT_providers_2","details":"Allows any hospital or clinic employee to refuse to participate in an abortion"},
{"state":"UT","law":"insurance","ID":"UT_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"UT","law":"insurance","ID":"UT_insurance_2","details":"Limits abortion coverage in all private health plans"},
{"state":"VA","law":"clinic","ID":"VA_clinic_1","details":"Requires patients to have an ultrasound before an abortion"},
{"state":"VA","law":"clinic","ID":"VA_clinic_2","details":"Requires the state to develop new regulations on abortion clinics"},
{"state":"VA","law":"counseling","ID":"VA_counseling_1","details":"Requires in-person counseling at least 24 hours before an abortion for some women"},
{"state":"VA","law":"insurance","ID":"VA_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"},
{"state":"WI","law":"clinic","ID":"WI_clinic_1","details":"Prohibits the use of telemedicine"},
{"state":"WI","law":"insurance","ID":"WI_insurance_1","details":"Limits abortion coverage in plans offered through the health insurance exchange"}]

